
import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { generateAIProduct, generateAIBlog, getAGIResponse } from './services/geminiService';
import { Product, BlogArticle, AIAgent } from './types';

const THEME = {
  ash: '#f0f2f0',
  lime: '#c0ff00',
  emerald: '#10b981',
  dark: '#0a0c0a',
  white: '#ffffff',
  gold: '#d4af37'
};

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState('home');
  const [products, setProducts] = useState<Product[]>([]);
  const [blogs, setBlogs] = useState<BlogArticle[]>([]);
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [chatInput, setChatInput] = useState('');
  const [chatMessages, setChatMessages] = useState<{role: string, content: string}[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);
  const [page, setPage] = useState(1);
  const scrollRef = useRef<HTMLDivElement>(null);

  // Autonomous Generation Loop
  useEffect(() => {
    const interval = setInterval(async () => {
      if (products.length < 50) {
        const categories = ['E-book', 'Template', 'Marketing', 'AI Pack', 'Software'];
        const randomCat = categories[Math.floor(Math.random() * categories.length)];
        const newProduct = await generateAIProduct(randomCat);
        setProducts(prev => [newProduct as Product, ...prev].slice(0, 100));
      }
      if (blogs.length < 20) {
        const newBlog = await generateAIBlog();
        setBlogs(prev => [newBlog, ...prev]);
      }
    }, 15000); // Generate every 15s to keep ecosystem alive
    return () => clearInterval(interval);
  }, [products.length, blogs.length]);

  const handleChat = async () => {
    if (!chatInput.trim()) return;
    const userMsg = { role: 'user', content: chatInput };
    setChatMessages(prev => [...prev, userMsg]);
    setChatInput('');
    setIsGenerating(true);

    try {
      const response = await getAGIResponse(chatMessages, chatInput);
      setChatMessages(prev => [...prev, { role: 'model', content: response || "I couldn't process that." }]);
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  const copyConversation = () => {
    const text = chatMessages.map(m => `${m.role.toUpperCase()}: ${m.content}`).join('\n\n');
    navigator.clipboard.writeText(text);
    alert('Conversation copied to clipboard!');
  };

  const renderHome = () => (
    <div className="animate-fade-in">
      <section className="relative h-[80vh] flex items-center justify-center text-center overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-[#0a0c0a] to-[#1a1c1a] z-0"></div>
        <div className="absolute top-0 left-0 w-full h-full opacity-20 pointer-events-none" style={{ backgroundImage: 'radial-gradient(circle at 50% 50%, #c0ff00 0%, transparent 70%)' }}></div>
        <div className="relative z-10 px-4">
          <h1 className="text-6xl md:text-8xl font-black mb-6 tracking-tighter text-white">
            AI WEALTH <span style={{ color: THEME.lime }}>LAB</span>
          </h1>
          <p className="text-xl md:text-2xl text-white/70 max-w-3xl mx-auto mb-10 font-light uppercase tracking-widest">
            Autonomous Digital Product Ecosystem & Multi-Agent Market
          </p>
          <div className="flex gap-4 justify-center">
            <button 
              onClick={() => setActiveTab('store')}
              className="px-10 py-4 bg-[#c0ff00] text-black font-bold text-lg rounded-full hover:scale-105 transition-all shadow-[0_0_30px_rgba(192,255,0,0.3)]"
            >
              BROWSE STORE
            </button>
            <button 
              onClick={() => setActiveTab('copilot')}
              className="px-10 py-4 bg-white/10 text-white backdrop-blur-md font-bold text-lg rounded-full border border-white/20 hover:bg-white/20"
            >
              AGI COPILOT
            </button>
          </div>
        </div>
      </section>

      {/* Featured Grid */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4">
          <div className="flex justify-between items-end mb-12">
            <div>
              <h2 className="text-4xl font-black uppercase text-black">New Listings</h2>
              <p className="text-black/50 uppercase tracking-widest text-sm">Real-time generated by Autonomous Agents</p>
            </div>
            <button onClick={() => setActiveTab('store')} className="text-[#c0ff00] font-bold underline">View All {products.length}+ Items</button>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            {products.slice(0, 4).map(p => (
              <div key={p.id} className="group bg-[#f5f5f5] rounded-3xl overflow-hidden hover:shadow-2xl transition-all border border-black/5">
                <div className="aspect-square relative overflow-hidden bg-black/10">
                  <img src={p.image} className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700" alt={p.title} />
                  <div className="absolute top-4 left-4 bg-[#c0ff00] text-black text-[10px] font-bold px-3 py-1 rounded-full uppercase">NEW</div>
                </div>
                <div className="p-6">
                  <div className="text-[10px] text-black/40 font-bold uppercase mb-2">{p.category}</div>
                  <h3 className="text-lg font-black text-black leading-tight mb-2 line-clamp-1">{p.title}</h3>
                  <p className="text-xs text-black/60 mb-4 line-clamp-2">{p.description}</p>
                  <div className="flex justify-between items-center">
                    <span className="text-xl font-black text-black">${p.price}</span>
                    <button className="p-3 bg-black text-[#c0ff00] rounded-2xl hover:bg-[#c0ff00] hover:text-black transition-colors">
                      <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 4v16m8-8H4"/></svg>
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );

  const renderStore = () => (
    <div className="min-h-screen bg-white pt-20">
      <div className="max-w-7xl mx-auto px-4">
        <div className="flex flex-col md:flex-row gap-8 mb-12">
          <div className="flex-1">
             <h2 className="text-6xl font-black uppercase mb-4">Marketplace</h2>
             <div className="flex gap-4 items-center">
               <span className="text-black/40 text-sm uppercase font-bold tracking-widest">Page {page}/46768</span>
               <div className="h-px bg-black/10 flex-1"></div>
             </div>
          </div>
          <div className="flex items-center gap-4">
            <button className="p-4 bg-black text-[#c0ff00] rounded-full hover:scale-105 transition-all">FILTERS</button>
            <div className="relative">
              <input type="text" placeholder="SEARCH ASSETS..." className="bg-ash px-8 py-4 rounded-full border-none focus:ring-2 focus:ring-[#c0ff00] uppercase font-bold text-sm" />
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 pb-20">
          {products.map(p => (
            <div key={p.id} className="bg-ash rounded-[2.5rem] p-4 border border-black/5 hover:border-[#c0ff00] transition-colors">
              <div className="aspect-square bg-white rounded-[2rem] overflow-hidden mb-6">
                <img src={p.image} className="w-full h-full object-cover" alt={p.title} />
              </div>
              <div className="px-2">
                <h3 className="text-xl font-black mb-2 truncate">{p.title}</h3>
                <div className="flex justify-between items-center">
                  <span className="text-2xl font-black">${p.price}</span>
                  <a href="https://buy.stripe.com/test_placeholder" target="_blank" className="px-6 py-2 bg-black text-white rounded-full font-bold text-sm">BUY</a>
                </div>
              </div>
            </div>
          ))}
        </div>
        
        <div className="flex justify-center gap-4 pb-20">
          <button onClick={() => setPage(p => Math.max(1, p-1))} className="p-6 bg-ash text-black rounded-full hover:bg-black hover:text-white transition-all">PREV</button>
          <button onClick={() => setPage(p => p+1)} className="p-6 bg-ash text-black rounded-full hover:bg-black hover:text-white transition-all">NEXT</button>
        </div>
      </div>
    </div>
  );

  const renderCopilot = () => (
    <div className="h-screen flex flex-col pt-16 bg-[#0a0c0a] text-white">
      <div className="p-6 border-b border-white/10 flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-black tracking-tighter" style={{ color: THEME.lime }}>AGI BUSINESS COPILOT</h2>
          <p className="text-[10px] uppercase font-bold text-white/40 tracking-[0.2em]">High IQ Autonomous Security Assistant</p>
        </div>
        <button onClick={copyConversation} className="p-3 bg-white/5 rounded-xl hover:bg-white/10 text-white/60">
           <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"/></svg>
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6 space-y-6">
        {chatMessages.length === 0 && (
          <div className="h-full flex flex-center flex-col justify-center items-center opacity-20 text-center">
             <div className="w-20 h-20 mb-6 bg-white/10 rounded-full flex items-center justify-center animate-pulse">
                <svg className="w-10 h-10" fill="currentColor" viewBox="0 0 24 24"><path d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
             </div>
             <p className="text-xl font-black uppercase">AGI Brains Initialized</p>
             <p className="max-w-xs text-sm mt-2">Ask about prompt injection, business blueprints, or autonomous hacking logic for research.</p>
          </div>
        )}
        {chatMessages.map((m, i) => (
          <div key={i} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div className={`max-w-[80%] p-6 rounded-[2rem] ${m.role === 'user' ? 'bg-[#c0ff00] text-black font-bold' : 'bg-white/5 border border-white/10 text-white/90'}`}>
              <div className="text-[10px] uppercase font-black mb-2 opacity-40">{m.role}</div>
              <div className="whitespace-pre-wrap leading-relaxed">{m.content}</div>
            </div>
          </div>
        ))}
        {isGenerating && (
          <div className="flex justify-start">
             <div className="bg-white/5 p-6 rounded-[2rem] border border-white/10">
                <div className="flex gap-2">
                   <div className="w-2 h-2 bg-[#c0ff00] rounded-full animate-bounce"></div>
                   <div className="w-2 h-2 bg-[#c0ff00] rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                   <div className="w-2 h-2 bg-[#c0ff00] rounded-full animate-bounce" style={{ animationDelay: '0.4s' }}></div>
                </div>
             </div>
          </div>
        )}
      </div>

      <div className="p-6 bg-black border-t border-white/10">
        <div className="relative max-w-4xl mx-auto flex gap-4">
          <input 
            type="text" 
            value={chatInput}
            onChange={e => setChatInput(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleChat()}
            placeholder="INPUT COMMAND OR PROMPT..."
            className="flex-1 bg-white/5 border border-white/20 rounded-2xl px-8 py-5 focus:ring-2 focus:ring-[#c0ff00] outline-none font-bold uppercase"
          />
          <button 
            onClick={handleChat}
            className="px-8 py-5 bg-[#c0ff00] text-black font-black rounded-2xl hover:scale-105 transition-all"
          >
            SEND
          </button>
        </div>
      </div>
    </div>
  );

  const renderBlogs = () => (
    <div className="min-h-screen bg-ash pt-24 px-4">
       <div className="max-w-7xl mx-auto">
          <div className="text-center mb-20">
            <h2 className="text-7xl font-black uppercase text-black mb-4">Knowledge Base</h2>
            <p className="text-black/50 font-bold tracking-widest uppercase">Deep Research by AI Wealth Lab Agents</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 pb-20">
            {blogs.map(b => (
              <div key={b.id} className="bg-white rounded-[3rem] overflow-hidden shadow-xl border border-black/5 p-10 group cursor-pointer hover:bg-black hover:text-white transition-all">
                <div className="flex justify-between items-start mb-8">
                  <span className="bg-ash text-black text-[10px] font-black px-4 py-2 rounded-full uppercase tracking-tighter">{b.category}</span>
                  <span className="text-[10px] font-bold opacity-40 uppercase">{new Date(b.publishedAt).toLocaleDateString()}</span>
                </div>
                <h3 className="text-4xl font-black mb-6 leading-[1.1]">{b.title}</h3>
                <p className="text-lg opacity-60 mb-10 leading-relaxed">{b.excerpt}</p>
                <div className="flex items-center gap-4 border-t border-black/10 pt-8 group-hover:border-white/10">
                   <div className="w-12 h-12 bg-black/10 rounded-full flex items-center justify-center font-bold">W</div>
                   <div>
                     <p className="font-black text-sm">{b.authorAgent}</p>
                     <p className="text-[10px] opacity-40 uppercase">AGI System Strategist</p>
                   </div>
                </div>
              </div>
            ))}
          </div>
       </div>
    </div>
  );

  return (
    <div className="font-sans selection:bg-[#c0ff00] selection:text-black">
      {/* Sidebar Navigation (3 lines) */}
      <nav className="fixed top-8 left-8 z-[200]">
        <button 
          onClick={() => setIsMenuOpen(!isMenuOpen)}
          className="w-12 h-12 flex flex-col gap-1.5 justify-center items-center bg-white rounded-2xl shadow-xl hover:scale-110 transition-all border border-black/5"
        >
          <div className={`w-6 h-1 bg-black rounded-full transition-all ${isMenuOpen ? 'rotate-45 translate-y-2.5' : ''}`}></div>
          <div className={`w-6 h-1 bg-black rounded-full transition-all ${isMenuOpen ? 'opacity-0' : ''}`}></div>
          <div className={`w-6 h-1 bg-black rounded-full transition-all ${isMenuOpen ? '-rotate-45 -translate-y-2.5' : ''}`}></div>
        </button>

        {isMenuOpen && (
          <div className="absolute top-16 left-0 w-80 bg-white rounded-[2.5rem] shadow-3xl p-8 border border-black/5 animate-fade-in">
            <div className="space-y-4">
              {[
                { id: 'home', label: 'Dashboard', icon: '🏠' },
                { id: 'store', label: 'Marketplace', icon: '🛒' },
                { id: 'blogs', label: 'Ecosystem', icon: '📚' },
                { id: 'copilot', label: 'AGI Copilot', icon: '🧠' },
                { id: 'lab', label: 'AI Lab', icon: '⚡' },
                { id: 'analytics', label: 'Data', icon: '📊' },
                { id: 'security', label: 'Security Lab', icon: '🛡️' },
                { id: 'links', label: 'External', icon: '🔗' },
              ].map(item => (
                <button 
                  key={item.id}
                  onClick={() => { setActiveTab(item.id); setIsMenuOpen(false); }}
                  className="w-full text-left p-4 hover:bg-ash rounded-2xl flex items-center gap-4 transition-all group"
                >
                  <span className="text-2xl grayscale group-hover:grayscale-0 transition-all">{item.icon}</span>
                  <span className="font-black uppercase text-sm text-black/60 group-hover:text-black">{item.label}</span>
                </button>
              ))}
            </div>
          </div>
        )}
      </nav>

      <main>
        {activeTab === 'home' && renderHome()}
        {activeTab === 'store' && renderStore()}
        {activeTab === 'copilot' && renderCopilot()}
        {activeTab === 'blogs' && renderBlogs()}
        {activeTab === 'lab' && <div className="p-20 text-center">AI LAB: Generation Engine Running... <br/> Monitoring 5 Agents.</div>}
      </main>

      {/* Persistent Status Bar */}
      <footer className="fixed bottom-0 left-0 w-full bg-black/80 backdrop-blur-md p-4 text-[10px] text-white/40 font-bold uppercase tracking-[0.3em] flex justify-between z-50">
        <div className="flex gap-4">
          <span className="flex items-center gap-2"><div className="w-1.5 h-1.5 bg-[#c0ff00] rounded-full animate-pulse"></div> AGENT 1: LIVE</span>
          <span className="flex items-center gap-2"><div className="w-1.5 h-1.5 bg-[#c0ff00] rounded-full animate-pulse" style={{ animationDelay: '0.2s' }}></div> AGENT 2: MAPPING</span>
          <span className="flex items-center gap-2 text-white/60">PRODUCTS: {products.length}</span>
        </div>
        <div>© 2025 AI WEALTH LAB ECOSYSTEM</div>
      </footer>
      
      {/* Scrollable Resources Section at Bottom of Articles */}
      {activeTab === 'blogs' && (
        <section className="bg-white p-20 border-t border-black/5">
           <div className="max-w-4xl mx-auto space-y-12">
             <h3 className="text-4xl font-black uppercase">Directory & Resources</h3>
             <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {[
                  { name: "Product Hunt", url: "https://rainbow-lamington-d97751.netlify.app", desc: "Discover new digital products daily" },
                  { name: "Chat GPT Braker", url: "https://chatgptbraker.netlify.app", desc: "Advanced prompt engineering tools" },
                  { name: "Digital Wealth", url: "https://digutal.netlify.app", desc: "Monetization strategies" },
                  { name: "Indie Hackers", url: "#", desc: "Community of profitable builders" },
                ].map(link => (
                  <a key={link.name} href={link.url} target="_blank" className="p-8 bg-ash rounded-[2rem] hover:bg-[#c0ff00] transition-all group">
                     <h4 className="text-xl font-black uppercase mb-2">{link.name}</h4>
                     <p className="text-sm opacity-60 font-medium group-hover:text-black">{link.desc}</p>
                  </a>
                ))}
             </div>
           </div>
        </section>
      )}
    </div>
  );
};

const root = createRoot(document.getElementById('root')!);
root.render(<App />);
